In [39]:
import numpy as np

In [40]:
import sklearn

In [41]:
myarr = np.array([[3,6,32,7]], np.int8)

In [42]:
myarr[0,2]

32

In [43]:
myarr.shape


(1, 4)

In [44]:
myarr.dtype

dtype('int8')

In [45]:
myarr[0,1]=4

In [46]:
myarr

array([[ 3,  4, 32,  7]], dtype=int8)

**Array creation: Conversion from other Python Structures

In [47]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
listarr.dtype

dtype('int32')

In [50]:
listarr.shape

(3, 3)

In [51]:
listarr.shape

(3, 3)

In [52]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [53]:
zeros = np.zeros((2,5))

In [54]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
zeros.dtype

dtype('float64')

In [56]:
zeros.shape

(2, 5)

In [57]:
rng = np.arange(15)

In [58]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
lspace = np.linspace(1,50,10)

In [62]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [67]:
emp = np.empty((4,6))

In [68]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 9.34604358e-307, 6.23058028e-307,
        9.34609790e-307, 1.24610723e-306, 1.42417629e-306],
       [7.56597770e-307, 1.02360867e-306, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 1.11260144e-306],
       [6.89812281e-307, 1.42418172e-306, 1.37961641e-306,
        1.39071445e-307, 8.45610231e-307, 8.45528067e-307]])

In [69]:
emp_like = np.empty_like(lspace)

In [70]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [71]:
ide = np.identity(45)

In [72]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [73]:
ide.shape

(45, 45)

In [75]:
arr = np.arange(99)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [79]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [81]:
arr=arr.reshape(3,33)

In [82]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [91]:
arr=arr.reshape(3,33)

In [92]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [93]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [94]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [96]:
ar=np.array(a)

In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
ar.sum(axis=0)

array([12, 15, 18])

In [99]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [100]:
 ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [101]:
ar.flat

In [102]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [104]:
ar.ndim

2

In [105]:
ar.size

9

In [106]:
 ar.nbytes

36

In [119]:
one = np.array([11,2,564,6,7])

In [115]:
one.argmax()

2

In [120]:
one.argmin()

1

In [121]:
one.argsort()

array([1, 3, 4, 0, 2], dtype=int64)

In [122]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [124]:
rarr=([[32,34,12],[23,45,34,],[545,674,23]])

In [125]:
rarr

[[32, 34, 12], [23, 45, 34], [545, 674, 23]]

In [127]:
rarr = np.array([[32,34,12],[23,45,34,],[545,674,23]])

In [128]:
rarr

array([[ 32,  34,  12],
       [ 23,  45,  34],
       [545, 674,  23]])

In [130]:
rarr.argmin()

2

In [131]:
rarr.argmax()

7

In [134]:
rarr.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [135]:
rarr.argmax(axis=1)

array([1, 1, 1], dtype=int64)

In [136]:
rarr.sort()

In [137]:
rarr

array([[ 12,  32,  34],
       [ 23,  34,  45],
       [ 23, 545, 674]])

In [138]:
rarr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [139]:
rarr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [140]:
rarr.ravel()

array([ 12,  32,  34,  23,  34,  45,  23, 545, 674])

In [142]:
rarr.reshape(9,1)

array([[ 12],
       [ 32],
       [ 34],
       [ 23],
       [ 34],
       [ 45],
       [ 23],
       [545],
       [674]])

In [143]:
rarr2 = np.array([[1,4,1],[4,0,6],[5,7,2]])

In [144]:
rarr + rarr2

array([[ 13,  36,  35],
       [ 27,  34,  51],
       [ 28, 552, 676]])

In [145]:
[34,22] + [54,43]

[34, 22, 54, 43]

In [146]:
rarr * rarr2

array([[  12,  128,   34],
       [  92,    0,  270],
       [ 115, 3815, 1348]])

In [149]:
np.sqrt(rarr2)

array([[1.        , 2.        , 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.23606798, 2.64575131, 1.41421356]])

In [150]:
rarr2.sum()

30

In [151]:
rarr2.min()



3.3333333333333335

In [152]:
rarr2.max()

7

In [153]:
rarr2.mean()

3.3333333333333335

In [155]:
np.where(rarr2>5)

(array([1, 2], dtype=int64), array([2, 1], dtype=int64))

In [156]:
type(np.where(rarr2>5))

tuple

In [157]:
np.count_nonzero(rarr2)

8

In [158]:
np.nonzero(rarr2)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [159]:
np.all(rarr2)

False

In [160]:
rarr2[1,2]=0

In [161]:
np.nonzero(rarr2)

(array([0, 0, 0, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 0, 1, 2], dtype=int64))

In [162]:
import sys

In [164]:
py_ar = [0,4,55,2]

In [165]:
np_ar = np.array(py_ar)

size difference between normal array and a numpy array

In [167]:
sys.getsizeof(1) * len(py_ar)

112

In [168]:
np_ar.itemsize * np_ar.size

16

numpy array methods and attributes > docs.scipy.org > attributes - methods

master the basics and then search and use