# Tensorflow - Basics

Tensor is a multi-dimensional array with the ability to run on GPU. 
* Vector is a 1D tensor while matrix is a 2D tensor.

#### Content
1. Initializing a Tensor
2. Mathematical Opertations
3. Indexing
4. Reshaping

In [7]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [8]:
import tensorflow as tf

In [9]:
tf.__version__

'2.13.0'

1. Initializing

In [10]:
x = tf.constant(4, shape = (1,1), dtype = tf.float32)
print(x)

# constant = it creates a constant tensor

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [11]:
y = tf.constant([[1,2,3],[1,4,9]], shape = (3,2), dtype=tf.float32)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 1.]
 [4. 9.]], shape=(3, 2), dtype=float32)


In [12]:
z = tf.ones((3,3))
print(z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [13]:
I = tf.eye(3, dtype=tf.int32) #3x3 Identity Matrix
print(I)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [14]:
a = tf.random.normal((2,3,4), mean=10, stddev = 2)
print(a)

# 2x3x4 matrix with random values satisfying the mean and standard deviation conditions
# It generates random numbers from a normal (Gaussian) distribution

tf.Tensor(
[[[13.12718   12.471907  13.930555  10.835753 ]
  [11.5335455 10.951491   9.173485   8.482625 ]
  [12.417412  10.882833  11.517947   9.440398 ]]

 [[10.715746  12.254726  13.517234  10.355448 ]
  [ 6.4330626 13.328953  10.438376   9.978434 ]
  [ 8.817421   8.51981    7.075349   8.783249 ]]], shape=(2, 3, 4), dtype=float32)


In [15]:
b = tf.random.uniform((2,3,4), minval=13, maxval=15)
print(b)

# 2x3x4 matrix with random uniform values satisfying the min and max conditions
# It generates random numbers from a uniform distribution.

tf.Tensor(
[[[14.880133 13.516994 13.347633 13.376392]
  [14.355269 14.918613 13.71964  14.242519]
  [14.14897  14.704    14.701882 13.006413]]

 [[14.617872 14.576204 13.949249 13.833039]
  [13.016829 14.662282 13.284806 13.301938]
  [13.807469 13.398827 13.440346 14.817137]]], shape=(2, 3, 4), dtype=float32)


In [16]:
c = tf.range(start=4, limit = 20, delta=4)
print(c)

tf.Tensor([ 4  8 12 16], shape=(4,), dtype=int32)


In [17]:
d = tf.cast(c, dtype=tf.float64)
print(d)
#tf.float - 16,32,64
#tf.int - 8,16,32,64
#tf.bool

tf.Tensor([ 4.  8. 12. 16.], shape=(4,), dtype=float64)


In TensorFlow, tf.reduce_sum and tf.math.reduce_sum are functions used to compute the sum of tensor elements along specified axes, while tf.math.sum is used to compute the sum of tensor elements without any axis specification.

In [18]:
import numpy as np

# Create a tensor
tensor = tf.constant([[1, 2, 3], [1, 4, 9]])

# Compute the sum of all elements in the tensor
sum_all = tf.reduce_sum(tensor)
print("Sum of all elements:", sum_all.numpy())

# Compute the sum along the rows (axis=0)
sum_rows = tf.reduce_sum(tensor, axis=0)
print("Sum along rows:", sum_rows.numpy())

# Compute the sum along the columns (axis=1)
sum_cols = tf.reduce_sum(tensor, axis=1)
print("Sum along columns:", sum_cols.numpy())

# Create another tensor
tensor2 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Compute the mean of all elements in the tensor
mean_all = tf.reduce_mean(tensor2)
print("Mean of all elements:", mean_all.numpy())

# Compute the mean along the rows (axis=0)
mean_rows = tf.reduce_mean(tensor2, axis=0)
print("Mean along rows:", mean_rows.numpy())

# Compute the mean along the columns (axis=1)
mean_cols = tf.reduce_mean(tensor2, axis=1)
print("Mean along columns:", mean_cols.numpy())


Sum of all elements: 20
Sum along rows: [ 2  6 12]
Sum along columns: [ 6 14]
Mean of all elements: 3.5
Mean along rows: [2.5 3.5 4.5]
Mean along columns: [2. 5.]


2. Mathmatical Operations

In [19]:
x = tf.constant([1,4,9])
y = tf.constant([1,16,81])

In [20]:
z = tf.add(x,y)
# or z = x+y
print(z)

tf.Tensor([ 2 20 90], shape=(3,), dtype=int32)


In [21]:
z = tf.subtract(x,y)
# or z = x-y
print(z)

tf.Tensor([  0 -12 -72], shape=(3,), dtype=int32)


In [22]:
z = tf.divide(y, x)
# or z = y/x
print(z)

tf.Tensor([1. 4. 9.], shape=(3,), dtype=float64)


In [23]:
z = tf.multiply(x, y)
# or z  = x*y
print(z)

tf.Tensor([  1  64 729], shape=(3,), dtype=int32)


In [24]:
z = tf.tensordot(x, y, axes=1)
print(z)

# or z = tf.reduce_sum(x*y, axis=0)
# dot product- element wise multiplication and then summation

tf.Tensor(794, shape=(), dtype=int32)


In [25]:
z = x ** 5
print(z)

# z = x^5

tf.Tensor([    1  1024 59049], shape=(3,), dtype=int32)


In [26]:
r1 = tf.random.normal((2,3))
r2 = tf.random.normal((3,4))

z = tf.matmul(r1,r2)
print(z)

# or

z = r1 @ r2
print(z)

# matrix multiplication

tf.Tensor(
[[ 0.55663544  0.29739365 -0.07215602 -0.12179293]
 [ 1.0775707  -0.5615735   1.2684621  -3.6024323 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.55663544  0.29739365 -0.07215602 -0.12179293]
 [ 1.0775707  -0.5615735   1.2684621  -3.6024323 ]], shape=(2, 4), dtype=float32)


In [27]:
mat = tf.constant([[1,2,3],[3,4,6],[2,8,3]], dtype=tf.float32)
temp_inv = tf.linalg.inv(mat)
print(temp_inv)

tf.Tensor(
[[-2.0000000e+00  1.0000000e+00 -1.9868216e-08]
 [ 1.6666669e-01 -1.6666669e-01  1.6666669e-01]
 [ 8.8888890e-01 -2.2222222e-01 -1.1111111e-01]], shape=(3, 3), dtype=float32)


Functions

In [28]:
# Create a tensor
x = tf.constant([1.0, -4.0, 64.0])

# Compute element-wise exponential and logarithm
exp_x = tf.math.exp(x)
log_x = tf.math.log(x)

# Compute element-wise trigonometric functions
sin_x = tf.math.sin(x)
cos_x = tf.math.cos(x)
tan_x = tf.math.tan(x)

# Compute element-wise square and square root
square_x = tf.math.square(x)
sqrt_x = tf.math.sqrt(x)

# Compute element-wise absolute value and sign
abs_x = tf.math.abs(x)
sign_x = tf.math.sign(x)

# Print the results
print("Input tensor: ", x.numpy())
print("Element-wise exponential: ", exp_x.numpy())
print("Element-wise logarithm: ", log_x.numpy())
print("Element-wise sine: ", sin_x.numpy())
print("Element-wise cosine: ", cos_x.numpy())
print("Element-wise tangent: ", tan_x.numpy())
print("Element-wise square: ", square_x.numpy())
print("Element-wise square root: ", sqrt_x.numpy())
print("Element-wise absolute value: ", abs_x.numpy())
print("Element-wise sign: ", sign_x.numpy())

Input tensor:  [ 1. -4. 64.]
Element-wise exponential:  [2.7182817e+00 1.8315639e-02 6.2351488e+27]
Element-wise logarithm:  [0.            nan 4.158883]
Element-wise sine:  [0.84147096 0.7568025  0.92002606]
Element-wise cosine:  [ 0.5403023  -0.6536436   0.39185724]
Element-wise tangent:  [ 1.5574077 -1.1578213  2.3478603]
Element-wise square:  [1.000e+00 1.600e+01 4.096e+03]
Element-wise square root:  [ 1. nan  8.]
Element-wise absolute value:  [ 1.  4. 64.]
Element-wise sign:  [ 1. -1.  1.]


In [29]:
# Create a tensor
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Use tf.gather to gather slices along a specified axis
gathered_axis0 = tf.gather(tensor, [0, 2], axis=0)
gathered_axis1 = tf.gather(tensor, [1, 2], axis=1)

print("Original tensor:\n", tensor.numpy())
print("Gathered slices along axis 0:\n", gathered_axis0.numpy())
print("Gathered slices along axis 1:\n", gathered_axis1.numpy())

# Create a boolean condition mask
mask = tf.constant([True, False, True])

# Use tf.boolean_mask to mask the tensor
masked_tensor = tf.boolean_mask(tensor, mask)

print("Original tensor:\n", tensor.numpy())
print("Masked tensor:\n", masked_tensor.numpy())


Original tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Gathered slices along axis 0:
 [[1 2 3]
 [7 8 9]]
Gathered slices along axis 1:
 [[2 3]
 [5 6]
 [8 9]]
Original tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Masked tensor:
 [[1 2 3]
 [7 8 9]]


In [30]:
# Concatenating tensors along a specified axis
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor2 = tf.constant([[7, 8, 9], [10, 11, 12]])
concatenated_tensor = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated tensor:")
print(concatenated_tensor.numpy())

# Stacking tensors along a specified axis
tensor3 = tf.constant([[13, 14, 15], [16, 17, 18]])
stacked_tensor = tf.stack([tensor1, tensor2, tensor3], axis=0)
print("Stacked tensor:")
print(stacked_tensor.numpy())

# Splitting a tensor into multiple tensors along a specified axis
split_tensors = tf.split(concatenated_tensor, num_or_size_splits=4, axis=0)
print("Split tensors:")
for tensor in split_tensors:
    print(tensor.numpy())

# Computing the minimum and maximum values along specified axes
min_value = tf.reduce_min(concatenated_tensor, axis=0)
max_value = tf.reduce_max(concatenated_tensor, axis=1)
print("Minimum values:")
print(min_value.numpy())
print("Maximum values:")
print(max_value.numpy())

# Computing the product of tensor elements along specified axes
product = tf.reduce_prod(concatenated_tensor, axis=1)
print("Product of tensor elements:")
print(product.numpy())

# Checking if any or all elements along specified axes satisfy a condition
any_elements_gt_10 = tf.reduce_any(concatenated_tensor > 10, axis=1)
all_elements_gt_5 = tf.reduce_all(concatenated_tensor > 5, axis=0)
print("Any elements greater than 10:")
print(any_elements_gt_10.numpy())
print("All elements greater than 5:")
print(all_elements_gt_5.numpy())

# Finding the k largest or smallest values and indices in a tensor
values, indices = tf.math.top_k(concatenated_tensor, k=2)
print("Top 2 values:")
print(values.numpy())
print("Indices of top 2 values:")
print(indices.numpy())


Concatenated tensor:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Stacked tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Split tensors:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
[[10 11 12]]
Minimum values:
[1 2 3]
Maximum values:
[ 3  6  9 12]
Product of tensor elements:
[   6  120  504 1320]
Any elements greater than 10:
[False False False  True]
All elements greater than 5:
[False False False]
Top 2 values:
[[ 3  2]
 [ 6  5]
 [ 9  8]
 [12 11]]
Indices of top 2 values:
[[2 1]
 [2 1]
 [2 1]
 [2 1]]


3. Indexing

In [31]:
temp = tf.constant([0,1,1,2,3,5,8,13,21,34])
print(temp[4:8]) #print in range
print(temp[::2]) #print with custom step size

tf.Tensor([ 3  5  8 13], shape=(4,), dtype=int32)
tf.Tensor([ 0  1  3  8 21], shape=(5,), dtype=int32)


In [32]:
print(temp[::-1])
#reverse

tf.Tensor([34 21 13  8  5  3  2  1  1  0], shape=(10,), dtype=int32)


In [33]:
indices = tf.constant([1, 4, 6])
x_ind = tf.gather(temp, indices)
print(x_ind)

tf.Tensor([1 3 8], shape=(3,), dtype=int32)


In [34]:
temp = tf.constant([[1,2,4,8,16],
                   [1,4,8,16,32],
                   [1,8,16,32,64]])
print(temp[0, 1:4])

tf.Tensor([2 4 8], shape=(3,), dtype=int32)


In [35]:
print(temp[0:2])

tf.Tensor(
[[ 1  2  4  8 16]
 [ 1  4  8 16 32]], shape=(2, 5), dtype=int32)


4. Reshaping

In [36]:
x = tf.range(12) ** 2
print(x)

tf.Tensor([  0   1   4   9  16  25  36  49  64  81 100 121], shape=(12,), dtype=int32)


In [37]:
x = tf.reshape(x, (2,2,3))
print(x)

tf.Tensor(
[[[  0   1   4]
  [  9  16  25]]

 [[ 36  49  64]
  [ 81 100 121]]], shape=(2, 2, 3), dtype=int32)


In [38]:
temp = tf.reshape(x, (4,3))
print(temp)

tf.Tensor(
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]], shape=(4, 3), dtype=int32)


In [39]:
temp = tf.transpose(temp)
print(temp)

temp2 = tf.transpose(temp, perm=[1,0])
print(temp2)

tf.Tensor(
[[  0   9  36  81]
 [  1  16  49 100]
 [  4  25  64 121]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]], shape=(4, 3), dtype=int32)
